procps.lo: /home/ringo/NetBeansProjects/php5-procps/procps.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ringo/NetBeansProjects/php5-procps $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ringo/NetBeansProjects/php5-procps/procps.c -o procps.lo 
$(phplibdir)/procps.la: ./procps.la
	$(LIBTOOL) --mode=install cp ./procps.la $(phplibdir)

./procps.la: $(shared_objects_procps) $(PROCPS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_procps) $(PROCPS_SHARED_LIBADD)

